languages = {
    "vi": {
        "title": "Công cụ Tự động Telegram TData",
        "choose_folder": "Chọn thư mục",
        "save_path": "💾 Lưu đường dẫn",
        "login_all": "🔐 Telethon",
        "auto_it": "🤖 AutoIT",
        "check_live": "🔍 Check live",
        "report": "📝 Report",
        "copy_telegram": "📋 Copy Telegram Portable",
        "open_telegram": "🟢 Mở Telegram Copies",
        "close_telegram": "❌ Đóng All Telegram",
        "arrange_telegram": "🟣 Sắp xếp Telegram",
        "check_update": "🔄 Check for Updates",
        "stats_label": "Bảng thống kê thư mục con:",
        "account_summary": "Thống kê tài khoản:",
        "logged_accounts": "Tài khoản đã đăng nhập:",
        "log_label": "Tiến trình:",
        "telegram_path_label": "Đường dẫn Telegram:",
        "lang_select_title": "Chọn ngôn ngữ",
        "lang_vi": "Tiếng Việt",
        "lang_en": "English",
        "lang_zh": "中文",
        "msg_saved_path": "Đã lưu đường dẫn vào máy!",
        "msg_error_path": "Đường dẫn không hợp lệ!",
        "msg_copy_result": "Kết quả Copy",
        "msg_open_result": "Kết quả mở Telegram",
        "msg_login_complete": "Quá trình đăng nhập cho tất cả các tài khoản đã hoàn tất.",
        "msg_privacy_complete": "Đã cập nhật quyền riêng tư cho tất cả các tài khoản.",
        "already_logged": "Đã có session",
        "success": "Thành công",
        "failure": "Thất bại",
        "not_found": "Chưa có",
        "otp_prompt": "Nhập mã OTP gửi tới {phone}:",
        "phone_prompt": "Nhập số điện thoại cho tài khoản ở\n{folder}:",
        "2fa_error": "Không tìm thấy mật khẩu 2FA tự động cho {phone}.",
        "copy_success": "Copy telegram.exe thành công cho {phone}",
        "copy_skip": "{phone} đã có telegram.exe, bỏ qua.",
        "close_result": "Đóng All Telegram:\nĐã đóng: {closed}\nLỗi: {errors}",
        "arrange_result": "Đã sắp xếp {count} cửa sổ Telegram.",
        "update_available": "Phiên bản {version} có sẵn. Bạn có muốn cập nhật không?",
        "no_updates": "Bạn đã có phiên bản mới nhất.",
        "update_error": "Lỗi kiểm tra cập nhật.",
        "create_session": "Tạo session",
        "update_privacy": "Thay đổi Quyền riêng tư",
        "change_info": "Thay đổi Thông tin tài khoản",
        "popup_inactive_title": "Danh sách TData đã bị log out",
        "popup_inactive_copy": "Copy toàn bộ danh sách",
        "popup_inactive_delete": "Xóa tất cả thư mục không hoạt động",
        "copy_inactive": "Copy Tdata không hoạt động",
        "delete_inactive": "Xóa Tdata không hoạt động",
        "copy_table": "Copy table",
        "processing": "Đang xử lý",
        "skipped": "Bỏ qua",
        "not_checked": "Chưa check",
        "checking": "Đang check",
        "completed": "Hoàn thành",
        "exe_not_found": "Không tìm thấy exe",
        "not_active": "Không hoạt động",
        "live": "Live",
        "stt": "STT",
        "check_status": "Trạng thái check",
        "live_status": "Trạng thái Live",
        "start": "Bắt đầu",
        "pause": "Tạm dừng",
        "confirm": "Xác nhận",
        "check_live_title": "Check live - Danh sách TData",
        "login_window_title": "Tiến trình đăng nhập",
        "not_started": "Chưa chạy",
        "auto_it_in_development": "Chức năng AutoIT đang được phát triển.",
        "report_in_development": "Chức năng Report đang được phát triển.",
        "change_info_in_development": "Chức năng thay đổi thông tin tài khoản đang được phát triển.",
        "telethon_session_title": "Phiên Telethon - {phone}",
        "invalid_source_exe": "Source telegram.exe không hợp lệ!",
        "close_result_title": "Kết quả đóng"
    },
    "en": {
        "title": "SteveD tools",
        "choose_folder": "Choose Folder",
        "save_path": "💾 Save Path",
        "login_all": "🔐 Telethon",
        "auto_it": "🤖 AutoIT",
        "check_live": "🔍 Check live",
        "report": "📝 Report",
        "copy_telegram": "📋 Copy Telegram Portable",
        "open_telegram": "🟢 Open Telegram Copies",
        "close_telegram": "❌ Close All Telegram",
        "arrange_telegram": "🟣 Arrange Telegram",
        "check_update": "🔄 Check for Updates",
        "stats_label": "Folder Statistics:",
        "account_summary": "Account Summary:",
        "logged_accounts": "Logged In Accounts:",
        "log_label": "Log:",
        "telegram_path_label": "Telegram Path:",
        "lang_select_title": "Select Language",
        "lang_vi": "Tiếng Việt",
        "lang_en": "English",
        "lang_zh": "中文",
        "msg_saved_path": "Path saved successfully!",
        "msg_error_path": "Invalid path!",
        "msg_copy_result": "Copy Result",
        "msg_open_result": "Telegram Open Result",
        "msg_login_complete": "Login process completed for all accounts.",
        "msg_privacy_complete": "Privacy updated for all accounts.",
        "already_logged": "Already Logged In",
        "success": "Success",
        "failure": "Failure",
        "not_found": "Not Found",
        "otp_prompt": "Enter OTP sent to {phone}:",
        "phone_prompt": "Enter phone number for account in\n{folder}:",
        "2fa_error": "No automatic 2FA password found for {phone}.",
        "copy_success": "Copied telegram.exe successfully for {phone}",
        "copy_skip": "{phone} already has telegram.exe, skipped.",
        "close_result": "Close All Telegram:\nClosed: {closed}\nErrors: {errors}",
        "arrange_result": "Arranged {count} Telegram windows.",
        "update_available": "Version {version} is available. Do you want to update?",
        "no_updates": "You already have the latest version.",
        "update_error": "Error checking for updates.",
        "create_session": "Create Session",
        "update_privacy": "Update Privacy",
        "change_info": "Change Account Info",
        "popup_inactive_title": "Inactive TData Folders",
        "popup_inactive_copy": "Copy All Inactive",
        "popup_inactive_delete": "Delete All Inactive Folders",
        "copy_inactive": "Copy Inactive TData",
        "delete_inactive": "Delete Inactive TData",
        "copy_table": "Copy table",
        "processing": "Processing",
        "skipped": "Skipped",
        "not_checked": "Not checked",
        "checking": "Checking",
        "completed": "Completed",
        "exe_not_found": "Exe not found",
        "not_active": "Not active",
        "live": "Live",
        "stt": "No.",
        "check_status": "Check Status",
        "live_status": "Live Status",
        "start": "Start",
        "pause": "Pause",
        "confirm": "Confirm",
        "check_live_title": "Check live - TData List",
        "login_window_title": "Login Process",
        "not_started": "Not started",
        "auto_it_in_development": "AutoIT feature is under development.",
        "report_in_development": "Report feature is under development.",
        "change_info_in_development": "Change account info feature is under development.",
        "telethon_session_title": "Telethon Session - {phone}",
        "invalid_source_exe": "Invalid source telegram.exe!",
        "close_result_title": "Close Result"
    },
    "zh": {
        "title": "Telegram TData 自动工具",
        "choose_folder": "选择文件夹",
        "save_path": "💾 保存路径",
        "login_all": "🔐 Telethon",
        "auto_it": "🤖 AutoIT",
        "check_live": "🔍 Check live",
        "report": "📝 Report",
        "copy_telegram": "📋 复制 Telegram Portable",
        "open_telegram": "🟢 打开 Telegram 副本",
        "close_telegram": "❌ 关闭所有 Telegram",
        "arrange_telegram": "🟣 排列 Telegram",
        "check_update": "🔄 检查更新",
        "stats_label": "Folder Statistics:",
        "account_summary": "Account Summary:",
        "logged_accounts": "Logged In Accounts:",
        "log_label": "Log:",
        "telegram_path_label": "Telegram Path:",
        "lang_select_title": "Select Language",
        "lang_vi": "Tiếng Việt",
        "lang_en": "English",
        "lang_zh": "中文",
        "msg_saved_path": "Path saved successfully!",
        "msg_error_path": "Invalid path!",
        "msg_copy_result": "Copy Result",
        "msg_open_result": "Telegram Open Result",
        "msg_login_complete": "Login process completed for all accounts.",
        "msg_privacy_complete": "Privacy updated for all accounts.",
        "already_logged": "Already Logged In",
        "success": "Success",
        "failure": "Failure",
        "not_found": "Not Found",
        "otp_prompt": "Enter OTP sent to {phone}:",
        "phone_prompt": "Enter phone number for account in\n{folder}:",
        "2fa_error": "No automatic 2FA password found for {phone}.",
        "copy_success": "Copied telegram.exe successfully for {phone}",
        "copy_skip": "{phone} already has telegram.exe, skipped.",
        "close_result": "Close All Telegram:\nClosed: {closed}\nErrors: {errors}",
        "arrange_result": "Arranged {count} Telegram windows.",
        "update_available": "Version {version} is available. Do you want to update?",
        "no_updates": "You already have the latest version.",
        "update_error": "Error checking for updates.",
        "create_session": "Create Session",
        "update_privacy": "Update Privacy",
        "change_info": "Change Account Info",
        "popup_inactive_title": "Inactive TData Folders",
        "popup_inactive_copy": "Copy All Inactive",
        "popup_inactive_delete": "Delete All Inactive Folders",
        "copy_inactive": "Copy Inactive TData",
        "delete_inactive": "Delete Inactive TData",
        "copy_table": "Copy table",
        "processing": "Processing",
        "skipped": "Skipped",
        "not_checked": "Not checked",
        "checking": "Checking",
        "completed": "Completed",
        "exe_not_found": "Exe not found",
        "not_active": "Not active",
        "live": "Live",
        "stt": "No.",
        "check_status": "Check Status",
        "live_status": "Live Status",
        "start": "Start",
        "pause": "Pause",
        "confirm": "Confirm",
        "check_live_title": "Check live - TData List",
        "login_window_title": "登录进程",
        "not_started": "未开始",
        "auto_it_in_development": "AutoIT 功能正在开发中。",
        "report_in_development": "报告功能正在开发中。",
        "change_info_in_development": "更改账户信息功能正在开发中。",
        "telethon_session_title": "Telethon会话 - {phone}",
        "invalid_source_exe": "无效的 telegram.exe 源文件！",
        "close_result_title": "关闭结果"
    }
}