# core/language.py

languages = {
    "vi": {
        "title": "Công cụ Tự động Telegram TData",
        "choose_folder": "Chọn thư mục",
        "save_path": "💾 Lưu đường dẫn",
        "login_all": "🔐 Telethon",
        "auto_it": "🤖 AutoIT",
        "check_live": "🔍 Check live",
        "report": "📝 Report",
        "copy_telegram": "📋 Copy Telegram Portable",
        "open_telegram": "🟢 Mở Telegram Copies",
        "close_telegram": "❌ Đóng All Telegram",
        "arrange_telegram": "🟣 Sắp xếp Telegram",
        "check_update": "🔄 Check for Updates",
        "stats_label": "Bảng thống kê thư mục con:",
        "account_summary": "Thống kê tài khoản:",
        "logged_accounts": "Tài khoản đã đăng nhập:",
        "log_label": "Tiến trình:",
        "telegram_path_label": "Đường dẫn Telegram:",
        "lang_select_title": "Chọn ngôn ngữ",
        "lang_vi": "Tiếng Việt",
        "lang_en": "English",
        "lang_zh": "中文",
        "msg_saved_path": "Đã lưu đường dẫn vào máy!",
        "msg_error_path": "Đường dẫn không hợp lệ!",
        "msg_copy_result": "Kết quả Copy",
        "msg_open_result": "Kết quả mở Telegram",
        "msg_login_complete": "Quá trình đăng nhập cho tất cả các tài khoản đã hoàn tất.",
        "msg_privacy_complete": "Đã cập nhật quyền riêng tư cho tất cả các tài khoản.",
        "already_logged": "Đã có session",
        "success": "Thành công",
        "failure": "Thất bại",
        "not_found": "Chưa có",
        "otp_prompt": "Nhập mã OTP gửi tới {phone}:",
        "phone_prompt": "Nhập số điện thoại cho tài khoản ở\n{folder}:",
        "2fa_error": "Không tìm thấy mật khẩu 2FA tự động cho {phone}.",
        "copy_success": "Copy telegram.exe thành công cho {phone}",
        "copy_skip": "{phone} đã có telegram.exe, bỏ qua.",
        "close_result": "Đóng All Telegram:\nĐã đóng: {closed}\nLỗi: {errors}",
        "arrange_result": "Đã sắp xếp {count} cửa sổ Telegram.",
        "update_available": "Phiên bản {version} có sẵn. Bạn có muốn cập nhật không?",
        "no_updates": "Bạn đã có phiên bản mới nhất.",
        "update_error": "Lỗi kiểm tra cập nhật.",
        "create_session": "Tạo session",
        "update_privacy": "Thay đổi Quyền riêng tư",
        "change_info": "Thay đổi Thông tin tài khoản",
        "popup_inactive_title": "Danh sách TData đã bị log out",
        "popup_inactive_copy": "Copy toàn bộ danh sách",
        "popup_inactive_delete": "Xóa tất cả thư mục không hoạt động",
        "copy_inactive": "Copy Tdata không hoạt động",
        "delete_inactive": "Xóa Tdata không hoạt động",
        "copy_table": "Copy table",
        "processing": "Đang xử lý",
        "skipped": "Bỏ qua",
        "not_checked": "Chưa check",
        "checking": "Đang check",
        "completed": "Hoàn thành",
        "exe_not_found": "Không tìm thấy exe",
        "not_active": "Không hoạt động",
        "live": "Live",
        "stt": "STT",
        "check_status": "Trạng thái check",
        "live_status": "Trạng thái Live",
        "start": "Bắt đầu",
        "pause": "Tạm dừng",
        "confirm": "Xác nhận",
        "check_live_title": "Check live - Danh sách TData",
        "login_window_title": "Tiến trình đăng nhập",
        "not_started": "Chưa chạy",
        "auto_it_in_development": "Chức năng AutoIT đang được phát triển.",
        "report_in_development": "Chức năng Report đang được phát triển.",
        "change_info_in_development": "Chức năng thay đổi thông tin tài khoản đang được phát triển.",
        "telethon_session_title": "Phiên Telethon - {phone}",
        "invalid_source_exe": "Source telegram.exe không hợp lệ!",
        "close_result_title": "Kết quả đóng"
    },
    "en": {
        "title": "Telegram Auto Tool",
        "choose_folder": "Choose folder",
        "save_path": "💾 Save path",
        "login_all": "🔐 Telethon",
        "auto_it": "🤖 AutoIT",
        "check_live": "🔍 Check live",
        "report": "📝 Report",
        "copy_telegram": "📋 Copy Telegram Portable",
        "open_telegram": "🟢 Open Telegram Copies",
        "close_telegram": "❌ Close All Telegram",
        "arrange_telegram": "🟣 Arrange Telegram",
        "check_update": "🔄 Check for Updates",
        "stats_label": "Folder statistics:",
        "account_summary": "Account summary:",
        "logged_accounts": "Logged accounts:",
        "log_label": "Progress:",
        "telegram_path_label": "Telegram path:",
        "lang_select_title": "Select Language",
        "lang_vi": "Vietnamese",
        "lang_en": "English",
        "lang_zh": "Chinese",
        "msg_saved_path": "Path saved successfully!",
        "msg_error_path": "Invalid path!",
        "msg_copy_result": "Copy result",
        "msg_open_result": "Open result",
        "msg_login_complete": "Login completed for all accounts.",
        "msg_privacy_complete": "Privacy updated for all accounts.",
        "already_logged": "Session already exists",
        "success": "Success",
        "failure": "Failure",
        "not_found": "Not found",
        "otp_prompt": "Enter OTP for {phone}:",
        "phone_prompt": "Enter phone number for account in\n{folder}:",
        "2fa_error": "2FA password not found for {phone}.",
        "copy_success": "Successfully copied telegram.exe for {phone}",
        "copy_skip": "{phone} already has telegram.exe, skipping.",
        "close_result": "Closed All Telegram:\nClosed: {closed}\nErrors: {errors}",
        "arrange_result": "Arranged {count} Telegram windows.",
        "update_available": "Version {version} available. Would you like to update?",
        "no_updates": "You already have the latest version.",
        "update_error": "Update check error.",
        "create_session": "Create session",
        "update_privacy": "Change Privacy",
        "change_info": "Change Account Info",
        "popup_inactive_title": "TData list logged out",
        "popup_inactive_copy": "Copy all lists",
        "popup_inactive_delete": "Delete all inactive folders",
        "copy_inactive": "Copy inactive TData",
        "delete_inactive": "Delete inactive TData",
        "copy_table": "Copy table",
        "processing": "Processing",
        "skipped": "Skipped",
        "not_checked": "Not checked",
        "checking": "Checking",
        "completed": "Completed",
        "exe_not_found": "exe not found",
        "not_active": "Not active",
        "live": "Live",
        "stt": "STT",
        "check_status": "Check status",
        "live_status": "Live status",
        "start": "Start",
        "pause": "Pause",
        "confirm": "Confirm",
        "check_live_title": "Check live - TData list",
        "login_window_title": "Login Progress",
        "not_started": "Not started",
        "auto_it_in_development": "AutoIT feature is under development.",
        "report_in_development": "Report feature is under development.",
        "change_info_in_development": "Account info change feature is under development.",
        "telethon_session_title": "Telethon Session - {phone}",
        "invalid_source_exe": "Invalid telegram.exe source!",
        "close_result_title": "Close result"
    },
    "zh": {
        "title": "Telegram 自动工具",
        "choose_folder": "选择文件夹",
        "save_path": "💾 保存路径",
        # Add additional translations here...
    }
}

# Function to select language
def select_language(language_code="vi"):
    return languages.get(language_code, languages["vi"])

# Default language
lang = select_language()  # Default to Vietnamese
